#!/usr/bin/perl -w
#
#

use strict;
use warnings;
use Cwd 'abs_path';
use Env;

my $REAL_SSH="/usr/bin/ssh";

my $hostname = '';
my $key = '';

my $command = "$REAL_SSH -G " . join(' ', @ARGV);
my @lines = `$command`;

foreach(@lines) {
    chomp;
    $hostname = "$1.$2.$3.$4" if(/hostname\s(\d+).(\d+).(\d+).(\d+)/);
    $key = "$1" if(/identityfile\s(.*)/);
}

my $home = $ENV{"HOME"};
if($key ne '') {
	$key =~ s/\~/$home/g;

	my $addme = 1;

	# check if key is loaded
	my @loaded = `ssh-add -L`;
	foreach(@loaded) {
		if(/.*\s$key/) {
			$addme = 0;
			last;
		}
	}

    if(-f $key && $addme) {
		my $v=`ssh-add $key`;
    }
}

system($REAL_SSH, @ARGV);

if($key ne '') {
	my $d = `ssh-add -D`;
}
